version: '3.4'

services:
  demo.clientservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"
  demo.clientservice1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:5003"
  demo.productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:5002"
  demo.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"