version: '3.4'

services:
  demo.clientservice:
    image: ${DOCKER_REGISTRY}democlientservice
    build:
      context: .
      dockerfile: Demo.ClientService/Dockerfile
   depends_on:
      - demo.clientservice
  demo.clientservice1:
    image: ${DOCKER_REGISTRY}democlientservice1
    build:
      context: .
      dockerfile: Demo.ClientService1/Dockerfile
   depends_on:
      - demo.clientservice1
  demo.productservice:
    image: ${DOCKER_REGISTRY}demoproductservice
    build:
      context: .
      dockerfile: Demo.ProductService/Dockerfile
   depends_on:
      - demo.apigateway
  demo.apigateway:
    image: ${DOCKER_REGISTRY}apigateway
    build:
      context: .
      dockerfile: Demo.ApiGateWay/Dockerfile